config/routes.rb
Rails.application.routes.draw do
  # resources :users,only: [:show,:index]
  root to: 'homes#top'
  devise_for :users
  get 'home/about' => 'homes#about'
  resources :books do
    resource :favorites,only:[:create,:destroy]
    resources :post_comments,only:[:create,:destroy]
  end
  resources :users,only: [:show,:index,:edit,:update] do
    resource :relationships, only: [:create, :destroy]
    get "followings" => "relationships#followings",as:"followings"
    get "followers" => "relationships#followers",as:"followers"
  end
  get "search" => "searches#search"


end

app/models/book.rb
class Book < ApplicationRecord
	belongs_to :user
	has_many :favorites,dependent: :destroy
	# book.find(1).fav_users ⇒　book :id1がfavoriteにあるuser:idを持ってくる
	has_many :fav_users,through: :favorites,source: :user
	has_many :post_comments,dependent: :destroy
	has_many :view_counts,dependent: :destroy


	# 引数で渡されたユーザーIDが、Favoritesテーブル内に存在するか調べる
	def favorited_by?(user)
		favorites.where(user_id:user.id).exists?
	end

	validates :title, presence: true
	validates :body, presence: true, length: {maximum: 200}
	attribute :count, :integer, default: 0


	def self.search_for(content, method)
		if method == "perfect"
      Book.where(title: content)
    elsif method == "partial"
      Book.where("title LIKE ?","%" + content + "%")
    elsif method == "forward"
      Book.where("title LIKE ?",content + "%")
    elsif method == "backward"
      Book.where("title LIKE ?","%" + content)
     end
   end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :ensure_current_user,{only:[:edit,:update]}

  def ensure_current_user
    @book = Book.find(params[:id])
    unless @book.user === current_user
      redirect_to books_path
    end
  end

  def show
    @book_new= Book.new
    @book = Book.find(params[:id])
    unless ViewCount.find_by(user_id: current_user.id,book_id:@book.id)
      current_user.view_counts.create(book_id: @book.id)
    end
    @user = @book.user
    @book_comment = PostComment.new
  end

  def index
    # @books = Book.left_joins(:favorites).group(:book_id).order("count(user_id)desc")
    @books = Book.all
    # ソート機能
    @method = "new"
    @method = params[:method]
      if @method == "new"
    		@books = Book.all.order(created_at: "desc")
    	elsif @method == "rate"
    		@books = Book.all.order(rate: "desc")
    	else
  	  	now = Time.current
  	  	from = now.ago(6.day)
  	  	# book_idがfa
  	  	@books = Book.includes(:fav_users).
  	  		sort{|a,b|
  	  					b.fav_users.includes(:favorites).where(created_at: from...now).size <=>
  	  					a.fav_users.includes(:favorites).where(created_at: from...now).size
  	  		}
  	  end
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    # binding.pry
    if @book.save
      redirect_to book_path(@book), notice: "You have created book successfully."
    else
      @books = Book.all
      render 'index'
    end
  end

  def edit
    # if current_user
      @book = Book.find(params[:id])
    # end
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book), notice: "You have updated book successfully."
    else
      render "edit"
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title,:body,:rate)
  end

end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_comment-post.html.erb
   <%= form_with url:book_post_comments_path(book.id),model:[book,book_comment],remote: true do |f| %>
     <%= f.text_area :comment,rows:"5",colums:"10" %>
     <%= f.submit "送信" %>
   <% end %>

app/views/books/_comments.html.erb
<table>
  <% book.post_comments.each do |post_comment| %>
  <tr>
    <td>
      <%= link_to user_path(post_comment.user) do %>
        <%= attachment_image_tag(post_comment.user, :profile_image, :fill, 100, 100, fallback: "no-image-icon.jpg") %><br>
        <%= post_comment.user.name %>
      <% end %>
    </td>
    <td><%= post_comment.comment %></td>

      <% if post_comment.user == current_user %>
        <td>
        <%= link_to 'Destroy', book_post_comment_path(post_comment.book,post_comment), method: :delete,remote:true,data:{confirm:"削除しますか？"},class:"btn btn-sm btn-danger destroy_book_#{post_comment.id}"%>
        </td>
      <% end %>
   </tr>
   <% end %>
</table>

app/views/books/_comments_bu1.html.erb
 <% book.post_comments.each do |post_comment| %>

   <div>
     <%= link_to user_path(post_comment.user) do %>
       <%= attachment_image_tag(post_comment.user, :profile_image, :fill, 100, 100, fallback: "no-image-icon.jpg") %><br>
       <%= post_comment.user.name %>
     <% end %>
   </div>
   <div><%= post_comment.comment %></div>

     <% if post_comment.user == current_user %>
       <div>
       <%= link_to 'Destroy', book_post_comment_path(post_comment.book,post_comment), method: :delete,remote:true,data:{confirm:"削除しますか？"},class:"btn btn-sm btn-danger destroy_book_#{post_comment.id}"%>
       </div>
     <% end %>
   <% end %>

app/views/books/_favorite.html.erb
<!--いいね-->
 <% if book.favorited_by?(current_user) %>
     <%= link_to book_favorites_path(book),method: :delete,class:"fav-on",remote:true do %>
       ♥<%= book.favorites.count %>
     <% end %>
 <% else %>
     <%= link_to book_favorites_path(book),method: :post,remote:true do %>
       ♡<%= book.favorites.count %>
     <% end %>
 <% end %>

app/views/books/_form.html.erb
<%= form_with model:book,local:true do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control book_title' %>
  </div>
  <div class="form-group">
    <%= f.label :opinion %>
    <%= f.text_area :body, class: 'form-control book_body' %>
  </div>
  <!--評価-->
  <div class="form-group" id="star">
    <%= f.label :rate,"評価" %>
    <%= f.hidden_field :rate,id: :review_star %>
  </div>
  <!--評価js　rateカラムが空の場合は、評価を入力できる-->
  <% unless book.rate.present? %>
    <script>
      $("#star").raty({
        size:36,
        starOff:   "<%= asset_path("star-off.png") %>",
        starOn:    "<%= asset_path("star-on.png") %>",
        scoreName: "book[rate]",
      });
    </script>
  <% else %>
     <script>
         $("#star").raty({
           size: 20,
           starOff: "<%= asset_path("star-off.png") %>",
           starOn: "<%= asset_path("star-on.png") %>",
           readOnly: true,
           score: "<%= book.rate %>",
         });
       </script>
    <% end %>

  <div class="form-group">
    <%= f.submit class: 'btn btn-success' %>
  </div>
<% end %>

app/views/books/_index.html.erb
<table class='table table-hover table-inverse'>
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th colspan="3"></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% books.each do |book| %>
      <tr>
        <td><%= link_to user_path(book.user) do %>
          <%= attachment_image_tag(book.user, :profile_image, :fill, 50, 50, fallback: "no-image-icon.jpg") %>
          <% end %>
        </td>
        <td><%= link_to book.title, book_path(book),class: "book_#{book.id}" %></td>
        <td><%= book.body %></td>
        <!--いいね-->
        <td id="favorite-btn_<%= book.id %>">
          <%= render "books/favorite",book:book %>
        </td>
        <!--コメント件数-->
       <td>
         <%= "#{book.post_comments.count}コメント"%>
       </td>
       <!--評価の星表示-->
       <td id="star-rate-<%= book.id %>"></td>
       <script>
         $("#star-rate-<%= book.id %>").raty({
           size: 20,
           starOff: "<%= asset_path("star-off.png") %>",
           starOn: "<%= asset_path("star-on.png") %>",
           readOnly: true,
           score: "<%= book.rate %>",
         });
       </script>


       <!--閲覧数-->
       <td>
         <%= "閲覧数:#{book.view_counts.count}" %>
       </td>


      </tr>
    <% end %>
  </tbody>
</table>

app/views/books/_sort.html.erb
<!--新着順、いいね順、評価順-->
<%= form_with url:books_path,method: :get,local: true do |f| %>
  <%= f.select :method,({"新着順"=>"new","評価順"=>"rate","いいね順"=>"fav"}) %>
  <%= f.submit "検索" %>
<% end %>

app/views/books/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
  		<h1>Editing Book</h1>
    	<%= render 'layouts/errors', obj: @book %>
  		<%= render 'form', book: @book %>
  		<%= link_to 'Show', book_path(@book), class: "book_#{@book.id}" %> |
  		<%= link_to 'Back', books_path, class: "back" %>
  </div>
</div>

app/views/books/index.html.erb
<div class='container px-5 px-sm-0'>
  <%= render 'layouts/errors', obj: @book %>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'users/info', user: current_user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <%= render "sort",books: @books %>
      <h2>Books</h2>
      <%= render 'index', books: @books %>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<div class='container'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'users/info',user: @user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'form', book: @book_new %>
    </div>
    <div class='col-md-8 offset-md-1'>
  		<h2>Book detail</h2>
  		<table class='table'>
  		  <tr>
  		    <td>
  		      <%= link_to user_path(@book.user) do %>
            <%= attachment_image_tag(@book.user, :profile_image, :fill, 100, 100, fallback: "no-image-icon.jpg") %><br>
            <%= @book.user.name %>
            <% end %>
          </td>
          <td><%= link_to @book.title, book_path(@book) %></td>
          <td><%= @book.body %></td>

          <!--いいね-->
          <td id="favorite-btn_<%= @book.id %>">
            <%= render 'favorite', book: @book %>
          </td>

          <!--コメント件数-->
           <td>
             <%= "#{@book.post_comments.count}コメント"%>
           </td>
          <!--評価の星表示-->
           <td id="star-rate-<%= @book.id %>"></td>
           <script>
             $("#star-rate-<%= @book.id %>").raty({
               size: 36,
               starOff: "<%= asset_path("star-off.png") %>",
               starOn: "<%= asset_path("star-on.png") %>",
               readOnly: true,
               score: "<%= @book.rate %>",
             });
           </script>

          <!--投稿削除、編集-->
          <% if @book.user == current_user %>
           <td><%= link_to 'Edit', edit_book_path(@book), class: "btn btn-sm btn-success edit_book_#{@book.id}" %></td>
           <td><%= link_to 'Destroy', book_path(@book), method: :delete, data: { confirm: '本当に消しますか？' }, class: "btn btn-sm btn-danger destroy_book_#{@book.id}"%></td>
          <% end %>

          <td>
            <%= "閲覧数:#{@book.view_counts.count}" %>
          </td>
        </tr>
      </table>
      <!--コメント一覧-->
      <div id="comments">
        <%= render "comments", book: @book %>
      </div>

       <!--コメント投稿-->
       <div id="comment-post">
         <%= render "comment-post", book: @book,book_comment: @book_comment %>
      </div>
    </div>
  </div>
</div>